model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
max_steps = 400
batch_size = 256
rollouts_per_example = 16
learning_rate = 1.5e-5

[buffer]
online_difficulty_filtering = true

[sampling]
max_tokens = 7000

[[env]]
id = "irfanjamil/BlicketTest_CausalReasoning@0.1.2"
args = { num_examples = 250 }

[eval]
interval = 400                    # Evaluate every 400 steps

[[eval.env]]
id = "irfanjamil/BlicketTest_CausalReasoning@0.1.2"
num_examples = 100
rollouts_per_example = 3
