model = "allenai/OLMo-3-7B-Instruct"
max_steps = 300
batch_size = 240
rollouts_per_example = 12
learning_rate = 1.5e-5

[buffer]
online_difficulty_filtering = true

[sampling]
max_tokens = 7000

[[env]]
id = "irfanjamil/BlicketTest_CausalReasoning@0.1.0"
args = { num_examples = 250 }

[eval]
interval = 300                    # Evaluate every 500 steps

[[eval.env]]
id = "irfanjamil/BlicketTest_CausalReasoning@0.1.0"
num_examples = 100
rollouts_per_example = 3
